

JFLAGS = -g -d . -cp
JAVAC = javac
JAVA = java 
DIR = $(PWD)
FILE = $(PWD)/src/TestStack.java
FILES = $(PWD)/src/*.java


compile:
	$(JAVAC) $(JFLAGS) $(CLASSPATH_MAKE) $(FILES)

run:  
	compile
	@echo $(CLASSPATH_MAKE)
	@echo $(FILE)
	@echo $(FILES)
 			
 			
